[package]
name = "chico_server"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
chico_file = { path = "../chico_file" }

[lints]
workspace = true

[features]
# Treat warnings as a build error.
strict = []
default = ["strict"] 