[package]
name = "chico_server"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
chico_file = { path = "../chico_file" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1" , features = ["full"]}
hyper = { version = "1", features = ["full"] }
http = "1.0"

[dev-dependencies]
rstest = "0.24.0"
assert_cmd = "2.0"
tempfile = "3"
predicates = "3.1.3"


[lints]
workspace = true

[features]
# Treat warnings as a build error.
strict = []
default = ["strict"] 

[[bin]]
name = "chico"
path = "src/main.rs"