[package]
name = "chico_server"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true


[dependencies]
chico_file = { path = "../chico_file" }
clap = { version = "4.5", features = ["derive"] }
tokio = { version = "1" , features = ["full"]}

[dev-dependencies]
rstest = "0.24.0"

[lints]
workspace = true

[features]
# Treat warnings as a build error.
strict = []
default = ["strict"] 