[package]
name = "timeout_test"
version = "0.1.0"
edition = "2021"

[dependencies]
chico_file = { path = "chico_file" }
chico_server = { path = "chico_server" }

[[bin]]
name = "timeout_integration"
path = "test_integration.rs"