[package]
name = "crates_uri"
edition.workspace = true
version.workspace = true
authors.workspace = true
description.workspace = true
documentation.workspace = true

[dependencies]
http = "1.3"

[dev-dependencies]
rstest = "0.26.1"

[lints]
workspace = true
